# Generated by Django 4.2.3 on 2023-09-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
